version: 2
updates:
  # gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "chore"
      scope: "deps"
      prefix-development: "chore"
      scope-development: "deps-dev"
    groups:
      spring-framework:
        patterns:
          - "org.springframework*"
      test-dependencies:
        patterns:
          - "*test*"
          - "*junit*"

  # docker (includes both Dockerfile and docker-compose files)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      scope: "docker"
