services:
  prudentia-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prudentia-app
    container_name: prudentia-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_DB: ${POSTGRES_DB:-prudentia}
      POSTGRES_USER: ${POSTGRES_USER:-prudentia}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prudentia}
      POSTGRES_PORT: ${POSTGRES_PORT:-5433}
    depends_on:
      - postgres
    networks:
      - prudentia-network

  postgres:
    image: postgres:17.5-alpine
    container_name: prudentia-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-prudentia}
      POSTGRES_USER: ${POSTGRES_USER:-prudentia}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prudentia}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    networks:
      - prudentia-network

volumes:
  postgres_data:
    driver: local

networks:
  prudentia-network:
    driver: bridge
