services:
  postgres:
    image: postgres:17.5-alpine
    container_name: prudentia-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-prudentia}
      POSTGRES_USER: ${POSTGRES_USER:-prudentia}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prudentia}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    networks:
      - prudentia-network

volumes:
  postgres_data:
    driver: local

networks:
  prudentia-network:
    driver: bridge