name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  POSTGRES_DB: prudentia
  POSTGRES_USER: prudentia
  POSTGRES_PASSWORD: prudentia
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon --no-build-cache

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Test with Gradle and generate JaCoCo reports
        run: ./gradlew test jacocoTestReport --no-daemon --no-build-cache
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: gargantua-dev/prudentia
          files: build/reports/jacoco/test/jacocoTestReport.xml
